services:
  - type: web
    name: myshop2-new               # New unique service name
    env: python
    rootDir: myshop2                 # Keep this if your code is in this folder
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn myshop.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true          # New secret key
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: myshop2-db-new       # Match new database name
          property: connectionString

databases:
  - name: myshop2dbnew             # New unique database name
    databaseName: myshop2_new        # New database name in Postgres
    user: myshop2_new
